### ISSUE TITLE
compiled libqi-python for python 3.4 can't import it 

### ISSUE THREAD

**Issue by NoiZeR355** [aldebaran/libqi-python#2] opened 2016-04-28 11:44 UTC
Hi,

I compiled libqi-python for python 3.4 but when I'm trying to import it I got the following error. 

File "/lib/python3.4/site-packages/qi/**init**.py", line 85, in <module>
    from _qi import Application as _Application
ImportError: dynamic module does not define init function (PyInit__qi)

Does someone have a clue how I can fix that?

**Comment by robertanto** [comment] 2021-01-03 17:30
It seems from [StackOverflow1](https://stackoverflow.com/questions/8400244/boost-python-import-error-module-does-not-define-init-function) & [StackOverflow2](https://stackoverflow.com/questions/24226001/importerror-dynamic-module-does-not-define-init-function-initfizzbuzz) that the problem is in the way we compiled the libboost-python library.

**Comment by nyibbang** [comment] 2021-01-04 11:44
libqi-python is currently being ported to Python 3, but note that only Python 3.5+ will be supported.
The `team/platform/dev` branch contains the modifications related to Python 3.

**Comment by robertanto** [comment] 2021-01-04 12:05
Thank you #nyibbang for your help!

In my case, I have compiled on the Jetson TX2 Platform (arm).
As suggested in #9 I compiled the release 2.5 on Ubuntu 16.04 (container) using Boost 1.64.0 .
I compiled libboost_python.so.1.64.0 using python2.7.

Is there a way to overcome this problem?

```bash
File  "/usr/lib/python2.7/dist-packages/qi/__init__.py", line 88, in 
from _qi import Application as _Application
ImportError: dynamic module does not define init function (init_qi)```

**Comment by nyibbang** [comment] 2021-01-04 14:02
Which branch did you use to build libqi-python ?
Do you have a `_qi.so` library in your build directory ?

**Comment by robertanto** [comment] 2021-01-04 14:12
I built the branch "release-2.5" and applied these [patches](https://github.com/aldebaran/libqi-python/files/5365166/jetson.zip).

Yes, I have the _qi.so file.

**Comment by nyibbang** [comment] 2021-01-05 09:57
If you run "readelf -d _qi.so | grep init", do you see the `init_qi` symbol ?

**Comment by robertanto** [comment] 2021-01-05 10:05
No.

**Comment by nyibbang** [comment] 2021-01-05 10:10
Sorry, I meant `readelf -s _qi.so | grep init`

**Comment by robertanto** [comment] 2021-01-05 10:11
yes, i can see it!

**Comment by nyibbang** [comment] 2021-01-05 10:22
Check that the symbol is exposed correctly (in the readelf output, the content of the 6th column should be `DEFAULT`).
Then try setting the `PYTHONPATH` environment variable to the path containing the `_qi.so` library when running your python interpreter.

Also it seems you installed the qi python module using pip (from the path `/usr/lib/python2.7/dist-packages/qi`), which should come with its owns `_qi.so` library. But from what I understand you also compiled it from the sources ? also at the beginning, this was about Python 3.4, but there it seems you're using Python 2.7. I'm a bit confused.

**Comment by robertanto** [comment] 2021-01-05 10:27
I am sorry for that.

I am not the author of the issue. I have the same problem but with Python2.7. 
I have compiled the library on the Jetson TX2 Platform (arm) because I can't install it from pypi.
To do that, I created a Docker container with Ubuntu 16.04 and Boost 1.64.0.

I confirm that the content of the 6th column is DEFAULT!

**Comment by robertanto** [comment] 2021-01-05 10:34
> Then try setting the `PYTHONPATH` environment variable to the path containing the `_qi.so` library when running your python interpreter.

Same output.

**Comment by nyibbang** [comment] 2021-01-05 10:35
Okay I understand a bit better now, although I doubt the two issues are related. I'm going to close this issue and we can discuss your issue on #9

**Closed by nyibbang** 2021-01-05 10:35 UTC
